### ISSUE TITLE
[wrong calculation] Employees contract with a half hour in duty hours

### ISSUE THREAD

**Issue by rothirschtec** [marcok/odoo_modules#1]
If an employee has, for example a contract with a weekly amount of 38.5 duty hours then the overtime calculation rounds the half hour down. 

I configured
Monday: 08:00 hours
Tuesday: 08:00 hours
Wednesday: 08:00 hours
Thursday: 08:00 hours
Friday: 06:30 hours

The Addon shows and calculates the duty hours on Friday with 06:00 hours.

**Comment by marcok** [comment]
Unfortunately the calculation is done in the core resource get_working_hours_of_date
We check what we can do.

**Comment by rothirschtec** [comment]
﻿Ok thanks : )



Rothirsch Technologies
by Roberto Zingerle

 
Systemadministration
René Zingerle

T + 43 5244 62497
F + 43 5244 61411
M + 43 699 17150771 
r <mailto:r.zingerle@gasmotoren.at> ene@rothirsch-tec.at <mailto:ene@rothirsch-tec.at> 
www.rothirsch-tec.at <mailto:ene@rothirsch-tec.at> 

 
Roberto Zingerle Familie
Austraße 15
6200 Jenbach/Tirol
Österreich

http://www.roberto-zingerle.com/ <http://www.tischlerei-zingerle.com/>  

 
 
 
UID Nr: ATU33092907
Gerichtsstandort: Schwaz
Bank: Sparkasse Kufstein
IBAN: AT612050 6002 0000 4786
BIC: SPKUAT22XXX

 
Dieses Email ist nur fuer den Empfaenger bestimmt, an den es gerichtet ist und kann vertrauliches bzw. unter das Berufsgeheimnis fallendes Material enthalten. Sind Sie nicht der Empfaenger, so haben Sie diese E-Mail irrtuemlich erhalten und jegliche Verwendung, Veroeffentlichung, Weiterleitung, Abschrift oder jeglicher Druck dieser E-Mail ist strengstens untersagt. Weder die Tischlerei Zingerle noch der  Absender uebernehmen die Haftung fuer Viren; es obliegt Ihrer Verantwortung, die E-Mail und deren angehaengte Dateien (sofern vorhanden) auf Viren zu ueberpruefen.

This Email and any attached files are confidential. If you are not the intended recipient, any disclosure, reproduction, copying, distribution or other use of this communication is strictly prohibited.If you have received this communication in error, please notify the sender immediately and then delete this Email. The sender or Tischlerei Zingerle does not accept liability for the correct and complete

-----Original message-----
