### ISSUE TITLE
Semi-monthly time sheets

### ISSUE THREAD

**Issue by bradnelson** [marcok/odoo_modules#11]
We need to have semi-monthly time sheets that are to be validated on the 15th and last day of the month.   If it was every two weeks, we could just validate two timesheets, but because the time periods may not end on the last day of a week, it doesn't seem compatible with our use case.

Can we contract to get this added?  Please let me know.

**Comment by marcok** [comment]
Hi,
Actually I think this should be possible with current module without any adjustment, you can generate your TS as you like, there is no restriction in whole weeks or months.
Anyway, pls contact us our homepage bytebrand.net if you need adjustments, we just picked up development of the module again and now would be good time for additional stuff.
