### ISSUE TITLE
Is this compatible with Odoo 9?

### ISSUE THREAD

**Issue by ViktorNova** [marcok/odoo_modules#6]
This looks very cool! Is it compatible with Odoo 9, or only 8?

**Comment by marcok** [comment]
We did not tested yet with 9, but its on the roadmap.

**Comment by get2know** [comment]
Hi Marcok,

You module seems to be spot on what i am looking for, but not yet available for 9.0.
Could you give an update about the current roadmap for a 9.0 version?

Thanks!

**Comment by atthila83** [comment]
hi marko, do you have in mind to make an app also for android?

**Comment by marcok** [comment]
hi everybody,
The timeclock station we will not port to android.
The module itself still needs polishment, then we may also migrate it on odoo 9 as soon as our customer who is sponsoring it migrate it to 9....

**Comment by atthila83** [comment]
marko is it possible to have a zip package of the ios app? thanks
