### ISSUE TITLE
Wrong duty hours with leave days having decimals <> 0 (e.g. 0,5)

### ISSUE THREAD

**Issue by RenaudDesarzens** [marcok/odoo_modules#7]
I just tested your module and am very interested in using it with Odoo 8.

As far as I could see, duty hours is either set to zero or equals 1:1 the defined worktime in employees contract. But often we have leaves of less than 1,0 day and less than the worktime of that day.

Would it be possible to adopt over-/undertime calculation to take such situations into account?

Example:
Normal daily worktime defined = 8,5 hours
Employee requests a (paid) half day leave (e.g. afternoon) = 0,5 days or in that case 4,25 hours.
Duty hours for this day should then be 4,25 hours instead of the normal daily worktime of 8,5 hours.
Attendance of the employee is 07:00 - 09:00 and 09:15 - 12:15 = 5 hours

Over-/undertime for this day should be calculated like this:

Attendance (5 hours) -   duty hours (4,25 hours <- 8,5 normal daily worktime hours - 4,25 paid leave hours) =  overtime 0,75 hours

Without this and depending whether duty hours are set to zero or to 8,5 (in that case), calculation of over-/undertime gives either 5 hours overtime or 3,5 hours undertime.

It would be very useful to us if this could be implemented likewise.

Thanks in advance for it!
Renaud

**Comment by marcok** [comment]
Yea, we are aware of this problem and it would be harder to solve than it sounds.
Atm our users just don't batch in on days they work half of the day, so then the summary is correct.
Keep you updated as soon we add this feature.

**Comment by RenaudDesarzens** [comment]
Thanks for the answer, looking forward to it!
Regards, Renaud

2015-11-13 12:33 GMT+01:00 marcok <notifications@github.com>:

**Comment by marcok** [comment]
We recently published a bugfixed V8 and V9 Version of the module, pls check if your problem still exists.
