### ISSUE TITLE
Time calculations not correct

### ISSUE THREAD

**Issue by bradnelson** [marcok/odoo_modules#9]
I have the latest download from the main Odoo website installed.  I have been testing the iOS app for check in/out.

I just checked, and our server's date/time is correctly set to Pacific/Los Angeles time zone.  My Odoo account preferences also has the same time zone set.

Calculations do not come out correctly.  It appears some time comparisons are being mixed between local time zone and GMT.

Here is an example of actions (copied and pasted from Human Resources -> Time Tracking -> My Current Timesheet -> Attendances):
01/14/2016 18:01:03	Sign Out
01/14/2016 08:15:16	Sign In
01/13/2016 16:45:52	Sign Out
01/13/2016 08:10:36	Sign In

And the results:
Date			Attendance 	Total Timesheet      Difference 
01/01/2016	00:00		00:00			00:00
01/13/2016	07:50		00:00			07:50
01/14/2016	-13:25		00:00			-13:25
01/15/2016	02:01		00:00			02:01

			-03:34		00:00			-03:34

Obviously, I have not worked into Jan 15 - it is still the Jan 14th in my time zone, not 2:01 am on 15th!

Is this a potentially a configuration issue, or a bug?

**Comment by marcok** [comment]
We recently published a bugfixed V8 and V9 Version of the module, pls check if your problem still exists.
